
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { aiIndexData, Lang } from "./aiIndexData";

// Helper to fetch font as Base64/Binary (Reused from generatePdf.ts logic)
async function loadFonts(doc: jsPDF) {
    try {
        const fontUrl = window.location.origin + '/fonts/Roboto-Regular.ttf';
        console.log(`[PDF] Fetching font from: ${fontUrl}`);

        const response = await fetch(fontUrl);
        if (!response.ok) {
            throw new Error(`Failed to fetch font: ${response.status} ${response.statusText} at ${fontUrl}`);
        }

        const blob = await response.blob();

        return new Promise<void>((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => {
                if (typeof reader.result === 'string') {
                    const base64 = reader.result.split(',')[1];
                    if (base64) {
                        doc.addFileToVFS("Roboto-Regular.ttf", base64);
                        doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");
                        doc.addFont("Roboto-Regular.ttf", "Roboto", "bold");
                        console.log("[PDF] Font loaded and registered successfully");
                        resolve();
                    } else {
                        reject(new Error("Empty base64 result from FileReader"));
                    }
                } else {
                    reject(new Error("FileReader result is not a string"));
                }
            };
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });

    } catch (err) {
        console.error("Font loading error:", err);
        throw err;
    }
}

export const generateAiPdf = async (
    score: number,
    zoneKey: "architect" | "executive" | "legacy",
    lang: Lang
) => {
    const doc = new jsPDF();
    await loadFonts(doc);
    doc.setFont("Roboto");

    try {
        const contentVal = aiIndexData.content[lang];
        const zoneData = contentVal.zones[zoneKey];
        const deepThink = contentVal.deep_think[zoneKey];
        const reportText = contentVal.report;

        // Header
        doc.setFontSize(20);
        doc.setTextColor(40, 40, 40);
        doc.text("SAFAR ISAEV | AI Velocity Index", 14, 22);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Date: ${new Date().toLocaleDateString()} | ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 14, 28);

        // Score Section
        doc.setFontSize(40);
        // Colors matching zones: Red / Amber / Emerald
        if (zoneKey === 'legacy') doc.setTextColor(225, 29, 72); // Rose-500
        if (zoneKey === 'executive') doc.setTextColor(217, 119, 6); // Amber-600
        if (zoneKey === 'architect') doc.setTextColor(16, 185, 129); // Emerald-500

        doc.text(`${score}%`, 14, 50);

        // Badge
        doc.setFontSize(14);
        doc.text(zoneData.badge.toUpperCase(), 50, 48);

        // Reset color
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);

        // Title & Role
        doc.text(zoneData.title, 14, 65);
        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);
        doc.text(zoneData.desc, 14, 72);

        // Diagnosis
        autoTable(doc, {
            startY: 80,
            head: [[reportText.diagnosis_title]],
            body: [[deepThink.diagnosis]],
            styles: { font: "Roboto", fontSize: 11, cellPadding: 4 },
            headStyles: { fillColor: [40, 40, 40], textColor: 255, fontStyle: 'bold', font: "Roboto" }
        });

        // Imperatives
        const imperativesData = deepThink.imperatives.map(imp => [`${imp.title}\n${imp.desc}`]);
        // @ts-ignore
        const nextY = doc.lastAutoTable.finalY + 10;

        autoTable(doc, {
            startY: nextY,
            head: [[reportText.imperatives_title]],
            body: imperativesData,
            styles: { font: "Roboto", fontSize: 10, cellPadding: 4 },
            headStyles: { fillColor: [30, 30, 30], textColor: 255, font: "Roboto" },
            columnStyles: { 0: { cellWidth: 'auto' } }
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by safarisaev.ai", 14, 280);

        doc.save('Safar_Isaev_AI_Velocity_Protocol.pdf');
        console.log("AI PDF Generated Successfully");

    } catch (error) {
        console.error("PDF Generation Failed:", error);
        alert("Error generating PDF. Please check console.");
    }
};
