import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { REPORT_DATA } from "./reportContent";

// Helper to load font if needed (placeholder functionality)
// In a real scenario, you'd load a base64 font string or fetch a TTF
// import { myFontBase64 } from "./fonts"; 

export const generateEfficiencyReport = (
    score: number,
    revenue: string | number,
    zone: "red" | "green" | "yellow",
    lang: "en" | "ru"
) => {
    const doc = new jsPDF();
    const content = REPORT_DATA[lang][zone];

    // NOTE: Default jsPDF fonts do NOT support Cyrillic. 
    // To fix this, you must import a font file (e.g., Roboto-Regular.ttf) 
    // and add it: doc.addFont("path/to/font.ttf", "MyFont", "normal");
    // For now, we will assume English works fine, and Russian implies a need for a font.
    // We'll use a safe fallback or instructions.

    // If you add a font file to public/fonts/Roboto-Regular.ttf, you can fetch it:
    // fetch('/fonts/Roboto-Regular.ttf').then(res => res.arrayBuffer()).then(font => { ... })
    // For this synchronous implementation, we'll strive for best effort.

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text("SAFAR ISAEV | Efficiency Index", 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${new Date().toLocaleDateString()} | ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 14, 28);

    // Score Section
    doc.setFillColor(zone === "red" ? 220 : zone === "yellow" ? 220 : 220, 220, 220); // Light gray bg for now
    if (zone === "red") doc.setTextColor(220, 38, 38);
    if (zone === "yellow") doc.setTextColor(217, 119, 6);
    if (zone === "green") doc.setTextColor(22, 163, 74);

    doc.setFontSize(40);
    doc.text(`${score}%`, 14, 50);

    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60);
    doc.text(`${content.title}`, 14, 60);

    // Diagnosis
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const splitDiagnosis = doc.splitTextToSize(content.diagnosis, 180);
    doc.text(splitDiagnosis, 14, 75);

    let currentY = 90;

    // Imperatives Table
    autoTable(doc, {
        startY: currentY,
        head: [[lang === "ru" ? "Императив" : "Imperative", lang === "ru" ? "Действие" : "Action"]],
        body: content.imperatives.map(imp => [imp.title, imp.desc]),
        styles: { fontSize: 10, cellPadding: 5 },
        headStyles: { fillColor: [40, 40, 40] },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 50 } },
    });

    // @ts-ignore
    currentY = doc.lastAutoTable.finalY + 15;

    // Pitch / Offer
    doc.setFillColor(240, 240, 240);
    doc.rect(14, currentY, 182, 30, "F");

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(content.pitch.title, 20, currentY + 10);

    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    const splitPitch = doc.splitTextToSize(content.pitch.desc, 170);
    doc.text(splitPitch, 20, currentY + 18);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by safarisaev.ai", 14, 290);

    // Save
    doc.save(`efficiency-report-${new Date().toISOString().split('T')[0]}.pdf`);
};
