import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { REPORT_DATA } from "./reportContent";

// Helper to fetch font as Base64/Binary
async function loadFonts(doc: jsPDF) {
    try {
        const response = await fetch("https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf");
        if (!response.ok) throw new Error("Failed to load font");

        const buffer = await response.arrayBuffer();
        // jsPDF requires a binary string for addFileToVFS in some versions, 
        // but recent versions support Uint8Array or Base64.
        // Let's use a safe arrayBuffer -> binary string conversion or Base64.

        const blob = new Blob([buffer]);
        const reader = new FileReader();

        return new Promise<void>((resolve) => {
            reader.onload = () => {
                const base64 = (reader.result as string).split(',')[1];
                doc.addFileToVFS("Roboto-Medium.ttf", base64);
                doc.addFont("Roboto-Medium.ttf", "Roboto", "normal");
                resolve();
            };
            reader.readAsDataURL(blob);
        });
    } catch (err) {
        console.error("Font loading failed, falling back to standard fonts (Cyrillic may break)", err);
    }
}

export const generateEfficiencyReport = async (
    score: number,
    revenue: string | number,
    zone: "red" | "green" | "yellow",
    lang: "en" | "ru"
) => {
    const doc = new jsPDF();

    // 1. Load Custom Font for Cyrillic
    await loadFonts(doc);
    doc.setFont("Roboto");

    try {
        const content = REPORT_DATA[lang][zone];
        const revenueDisplay = revenue.toLocaleString();

        // Header
        doc.setFontSize(20);
        doc.setTextColor(40, 40, 40);
        doc.text("SAFAR ISAEV | Efficiency Audit", 14, 22);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Date: ${new Date().toLocaleDateString()} | ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 14, 28);

        // Score Section
        doc.setFontSize(40);
        doc.setTextColor(zone === 'red' ? '#e11d48' : zone === 'yellow' ? '#d97706' : '#059669');
        doc.text(`${score}%`, 14, 50);

        // Revenue Risk Context
        doc.setFontSize(10);
        doc.setTextColor(40, 40, 40);
        doc.text(`Est. Revenue Input: $${revenueDisplay}`, 50, 45); // Adjust position as needed

        // Reset color
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);

        // Title & Role
        doc.text(content.title, 14, 65);
        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);
        doc.text(content.role, 14, 72);

        // Diagnosis
        autoTable(doc, {
            startY: 80,
            head: [['DIAGNOSIS']],
            body: [[content.diagnosis]],
            styles: { font: "Roboto", fontSize: 11, cellPadding: 4 },
            headStyles: { fillColor: [40, 40, 40], textColor: 255, fontStyle: 'bold' }
        });

        // Imperatives
        const imperativesData = content.imperatives.map(imp => [`${imp.title}\n${imp.desc}`]);
        // @ts-ignore
        const nextY = doc.lastAutoTable.finalY + 10;

        autoTable(doc, {
            startY: nextY,
            head: [['STRATEGIC IMPERATIVES']],
            body: imperativesData,
            styles: { font: "Roboto", fontSize: 10, cellPadding: 4 },
            headStyles: { fillColor: [30, 30, 30], textColor: 255 },
            columnStyles: { 0: { cellWidth: 'auto' } }
        });

        // Pitch
        // @ts-ignore
        const finalY = doc.lastAutoTable.finalY + 10;

        autoTable(doc, {
            startY: finalY,
            head: [[content.pitch.title]],
            body: [[content.pitch.desc]],
            styles: { font: "Roboto", fontSize: 10, fillColor: [240, 240, 240], cellPadding: 6 },
            headStyles: { fillColor: [16, 185, 129], textColor: 255 } // Emerald-500
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by safarisaev.ai", 14, 280);

        doc.save('Safar_Isaev_Audit_Protocol.pdf');
        console.log("PDF Generated Successfully");

    } catch (error) {
        console.error("PDF Generation Failed:", error);
        alert("Error generating PDF. Please check console.");
    }
};
